#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Source system scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Merge Xresources
if [ -s "$XDG_CONFIG_HOME/X11/Xresources" ]; then
	xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"
fi

# Bind multimedia keys
if [ -s "$XDG_CONFIG_HOME/X11/xbindkeysrc" ]; then
	xbindkeys -f "$XDG_CONFIG_HOME/X11/xbindkeysrc"
fi

# xkb custom map
xkbcomp -I$HOME/.config/xkb $HOME/.config/xkb/mymap $DISPLAY

# Run local scripts
autorun-scripts

# Start WM
exec i3
