#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Source system scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Merge Xresources
if [ -s "$XDG_CONFIG_HOME/X11/Xresources" ]; then
	xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"
fi

# Bind multimedia keys
if [ -s "$XDG_CONFIG_HOME/X11/xbindkeysrc" ]; then
	xbindkeys -f "$XDG_CONFIG_HOME/X11/xbindkeysrc"
fi

# Caps lock is escape
setxkbmap -option ctrl:escape
# Left super is meta
setxkbmap -option altwin:meta_win
# Move right alt to mod3 (for WM)
xmodmap -e "remove mod1 = Alt_R" -e "add mod3 = Alt_R"

# Turn num lock on
numlockx &

# Run local scripts
autorun-scripts

# Start WM
exec i3
