#!/bin/bash

# Set brightness to sensible level
xbacklight -set 33

# Set up external mouse
xinput --set-prop 'Arc Touch BT Mouse' 'Device Accel Constant Deceleration' 4 &
xset mouse 4 6 &

# Check state of external monitors
monitor-toggle
