#!/bin/sh

cd /usr/lib/systemd/system/
while true
	do
		  service=$(stest -fl . \
		      | sort  \
			      | sed '1i[ list services ]\n[ list-unit-files ]' \
				      | dmenu -p 'Restart') || break
					   
					     case $service in
						     '[ list services ]')    /usr/bin/urxvt -title 'list services' -e systemctl -t service -a ;;
							     '[ list-unit-files ]')  /usr/bin/urxvt -title 'list-unit-files' -e systemctl list-unit-files ;;
								     *)                      sudo systemctl restart $service
									                             break
																                             ;;
																							   esac
																							   done
