#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Start D-Bus
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Sync Xresources
if [ -s ~/.Xresources ]; then
	xrdb -merge "$XDG_CONFIG_HOME/xorg/Xresources"
fi

# Bind multimedia keys
xbindkeys -f "$XDG_CONFIG_HOME/xorg/xbindkeysrc"

# Turn num lock on
numlockx &

# Run local scripts
autorun-scripts

# Start WM
exec i3
