#!/bin/bash

# Set brightness to sensible level
xbacklight -set 33

# Set up external mouse
xinput --set-prop 13 'Device Accel Constant Deceleration' 2 &
xset mouse 3 6 &

# Check state of external monitors
monitor-toggle
