#!/bin/bash

LAPTOP="eDP1"
HDMI="HDMI1"
VGA="DP1"
GAMMA="0.9:0.8:0.7"

if (xrandr | grep "$HDMI connected")
then
    xrandr --output $LAPTOP --gamma $GAMMA --auto --primary --output $HDMI --auto --above $LAPTOP
elif (xrandr | grep "^$VGA connected")
then
    xrandr --output $LAPTOP  --gamma $GAMMA --auto --primary --output $VGA --auto --above $LAPTOP
else
    xrandr --output $LAPTOP  --gamma $GAMMA --auto --output $HDMI --off --output $VGA --off
fi

# Re-adjust wallpaper
set-wallpaper
